# docker-compose file managing Nginx and the application
# Loading some variables from the .env file:
#   - DOMAIN: DNS domain name
#   - EMAIL: Maintainer email
#   - APP_FOLDER: Directory containing the application
#   - FLASK_APP: Flask entrypoint
#   - FLASK_ENV: Flask environment

version: "3.9"

services:
  application:
    build: ./${APP_FOLDER}
    command: gunicorn -c gunicorn.ini.py ${FLASK_APP}:app --timeout 10000 --workers 4
    environment:
      - FLASK_ENV=${FLASK_ENV}
    ports:
      - 10779:10779

volumes:
  redis-data:

networks:
  default:
    external:
      name: laradock_backend