# docker-compose file managing Nginx and the application
# Loading some variables from the .env file:
#   - DOMAIN: DNS domain name
#   - EMAIL: Maintainer email
#   - APP_FOLDER: Directory containing the application
#   - FLASK_APP: Flask entrypoint
#   - FLASK_ENV: Flask environment

version: "3.9"

services:
  nginx:
    build:
      context: ./nginx
      args:
        DOMAIN: ${DOMAIN}
        EMAIL: ${EMAIL}
        FLASK: application
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - application

  application:
    build: ./${APP_FOLDER}
    command: gunicorn -c gunicorn.ini.py ${FLASK_APP}:app --timeout 10000 --workers 2
    environment:
      - FLASK_ENV=${FLASK_ENV}
    ports:
      - 5000:5000
    depends_on:
      - redis
    links:
      - redis

  redis:
    image: redis:alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

volumes:
  redis-data: